### PR TITLE
Don't allow simple match to meet acronym threshold

### PR DESCRIPTION
**Pull request by sdbrannum**
**What**:

Added test case for acronym threshold.

**Why**:

Currently, the base simple match threshold is meeting the standard of the acronym threshold in certain instances.

**How**:

**Checklist**:

* [ ] Documentation
* [x] Tests
* [x] Ready to be merged 
* [ ] Added myself to contributors table

### CODE REVIEW

**Comment by kentcdodds** [comment]
Ah yes, this is definitely a bug. Would you be willing to add a commit for the fix? Thanks!

**Comment by sdbrannum** [comment]
@kentcdodds  I'd love to.  It may take a few days as I try to figure out the "correct" way to weight simple matches comparatively on a scale.

**Comment by kentcdodds** [comment]
Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @sdbrannum for code and tests

**Pull request merged**
