### PR TITLE
feat: support custom sorter

### PR DESCRIPTION
**Pull request by tannerlinsley**
Adds the ability to fully-control sorting

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Looks like some prettier functionality got carried away here? I’m not sure why that happened.

**Comment by tannerlinsley** [comment]
Wow, no matter what I commit, all of those prettier changes still happen. Any tips here?

**Comment by tannerlinsley** [comment]
Alright, it took some rebasing, cherry picking the lines and committing with `--no-verify` to get this to behave.

**Review by kentcdodds — APPROVED** [review]
Coolio! Thanks for working through this weird tooling stuff. Sorry about that. Thanks for the feature!

**Comment by kentcdodds** [comment]
@All-contributors please add @tannerlinsley for code and tests

**Pull request merged**
