### PR TITLE
feat: allow array notation in keys

### LINKED ISSUE #135: Can't figure out how to generate keys for use with recursive data
- `match-sorter` version: 6.3.1
- `node` version: 16.11.1

Relevant code or config

```javascript

```

What you did:

I'm trying to write a fuzzy text filter for use with some rows from a `react-table` instance. Working great! I'm able to pass rows with a generic type of data for each row (`TableDataType`), and create keys for each of the columns I'm searching on. My `ids` array are the column names. Some of them have nested keys like `name.first`, so I'm using a function to generate keys, looking inside the row's `values` array, then at the column inside it named whatever is in `id`. So far so good, I'm searching across all columns, even if they have dot notation names, via the functions I return here in `topLevelKeys`:

```typescript
export const fuzzyTextFilter = <TableDataType extends PanamaTable.CellDataCollection>(
  rows: Array<Row<TableDataType>>,
  ids: Array<IdType<TableDataType>>,
  filterValue: string,
): Row<TableDataType>[] => {
  if (!ids || !filterValue) {
    return rows;
  }

  /**
 * Map the array of properties to search into an array of functions that take a row and return 
 * the value at that id (inside the `values` object on a row).
 */
  const topLevelKeys: Array<ValueGetterKey<Row<TableDataType>>> = ids.map(
    (id) => (item: Row<TableDataType>) => item.values[id] as string,
  );

  // We may have sub rows, so generate nested keys for those too
  const subRowKeys = generateKeysForSubRows(rows, ids)

  return matchSorter(rows, filterValue, { keys: [...topLevelKeys, ...subRowKeys] });
};
```
You may notice a `subRowKeys` and that's where I'm running into problems. Essentially, each of the row's data objects (of type `TableDataType` here) may have `subRows`, of type `Array<Row<TableDataType>>` inside it. I'd *ALSO* like to generate functions to access the columns in each of those subRows.

Problem description:

Unfortunately, the nesting is theoretically infinite, and because of the possibility of having dots in the column names, I can't just use simple strings recursively till I run into the bottom row. I need to use functions. I've been struggling to figure out a way I can recursively pass a partially curried object that I want to keep pulling objects out of down the recursive stack. I can generate keys at any level (change the `item.values[id]` to `item.subRows.map(subRow => subRow.values[id])`, but I can't make that generalized.

So, my long-winded question is, is there a simpler way to do this? All I'm trying to do is search for values within an array, but be able to do so recursively.

Solution:

If it were possible to use the string notation syntax, ``key: `item.values.${id}` `` would be possible, and then I could just use a string recursively. However, that breaks because one of the values for `id` is `name.first`, which creates `item.values.name.first` instead of the valid accessor `item.values[name.first]`. If the array syntax was supported, my problem is solved.

Thanks so much for reading!!

### PR DESCRIPTION
**Pull request by dgattey**
**What**: Allows using array notation in keys (except for the wildcard value), making expressions like `foo[0].first` or `foo.*[complex.key].last` possible. Does so via a `matchAll` and a `replace` within the `getNestedValues` function. Backwards compatible with all the current tests, just adding support for the new syntax in addition to the currently-supported dot notation.

**Why**: Fixes #135 to allow for more complex expressions for array notation keys. Allows more compatibility with existing usage without breaking anything that already works.

**How**: Isolated where the keys were being split and converted to nested properties, then wrote a (failing at the time) test for new syntax. Then figured out how to split the keys array on a complex notation and iterated until it worked! Didn't fix the wildcard case, as there's no need to allow that to be in array notation.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by cschubiner** [comment]
I'd love for this to get in!

**Comment by kentcdodds** [comment]
Hmmm... What's the use case here? It just seems a little more complex than I would want it to be. Maybe there's a simpler approach that would satisfy the use case?

**Comment by dgattey** [comment]
The use case is for nested objects + keys that have periods in them (or other special characters):
```
{
  child: {
    basicKey: 'value',
    'complex.key': 'otherValue'
  }
}
```
I can't access that with any current `keys` syntax, as far as I understand the docs + code.

Happy to find a simpler use case! I couldn't think of another solution but I'm less familiar with the code than you of course.

**Comment by kentcdodds** [comment]
Maybe we could do what Remix does by wrapping anything we want escaped with `[` and `]`: https://github.com/remix-run/remix/blob/main/packages/remix-dev/config/routesConvention.ts: https://remix.run/docs/en/v1/api/conventions#escaping-special-characters

**Comment by dgattey** [comment]
Cool idea! Isn't that still going to be searching on something inside square brackets though? How exactly does that help other than reduce the scope of what we have to replace with a regex? Maybe that's all that you're looking for. Still have to do a search, but no need to cross reference the array of matches, I guess. Definitely a bit cleaner!

Will take a stab at it. Thanks for the speedy responses.

**Comment by dgattey** [comment]
@kentcdodds Huh, isn't that exactly what I'm doing here? I'm using anything surrounded with `[` and `]` as a single key, even if it contains `.` inside it. The code you linked from Remix is more complex, but looks like it accomplishes almost the same thing. The only difference would be multiple layers of `[ ]`, right? For a path segment, you're not going to need more than one layer of nesting, as far as I can tell.

I used `matchAll` from ES2020 instead of something compatible with node 10 and 12 like it looks like the checks run, but otherwise this would be ready to go. I'll fix it up to use `match` or something else that's a little more simple if possible. Otherwise, can you validate that there's not some subtle difference with the Remix code I'm missing? Thanks!

**Comment by kentcdodds** [comment]
What you have here could be fine. I think I'm just a bit confused by all the `*`s and stuff 🤔

**Comment by dgattey** [comment]
okay, figured out another way to accomplish what I want to with the callback type of `key`. Thanks for entertaining this idea! Basically, I mapped my results to a simpler nesting structure, then just used `keys` with an object instead of a string to pull out what I needed. No need for this after all.

**Pull request closed without merging**
