### PR TITLE
chore(build): add rollup to bundle external deps

### PR DESCRIPTION
**Pull request by kentcdodds**
Decided to go with rollup so we could benefit from reducing closures created by webpack and also because I wanted to learn something new.

I tested this and we should be able to add dependencies and import them with ES6 modules and benefit from treeshaking when possible, which is neat.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Do you got a second to give this a look @conorhastings? Thoughts?

**Comment by kentcdodds** [comment]
:shipit:

**Comment by conorhastings** [comment]
nice, LGTM. I've been meaning to try rollup as well, seems like it's going to be the way to go for libraries with apps staying in webpack land.

**Comment by kentcdodds** [comment]
Yeah, I agree. Though I'd love Webpack to get the same features so I can have one tool for both.

**Pull request merged**
