### PR TITLE
feat: add sort items alphabetically test case

### PR DESCRIPTION
**Pull request by mrceperka**
**What**: Extra test case for alphabetical sorting.

**Why**: Because alphabetical sorting is expected and desired behavior.

**How**: TODO

**Checklist**:

- [ ] Documentation
- [x] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
Would you be willing to add your suggested change to fix this?

**Comment by mrceperka** [comment]
Yeah, will do asap.

**Comment by kentcdodds** [comment]
I've thought about a different breaking change I want to make. I don't like the `CASE_RANKINGS` feature at all and that's what's causing these issues. So I'll remove that feature (and show a workaround) and that'll fix this. Thanks!

**Comment by mrceperka** [comment]
@kentcdodds Cool, that's even better :)

**Pull request closed without merging**
