### PR TITLE
feat: add baseSort configuration option

### PR DESCRIPTION
**Pull request by tannerlinsley**
**What**: Added a baseSort configuration option

**Why**: Ability to override the default stable sort for tie-breaker items

**How**: By adding a new configuration option and implementing some inversion of control and a new default

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      
- [x] Added myself to contributors table (I'm assuming I can do this with the bot after this)

### CODE REVIEW

**Comment by tannerlinsley** [comment]
@all-contributors please add tannerlinsley for code

**Comment by tannerlinsley** [comment]
Looks like the test failed, but I can't really decipher why.

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
